title: SoumyaK4
description: Martial Arts for Body & Brain
theme: just-the-docs
color_scheme: sdark
url: https://soumyak4.in

logo: "/assets/images/Logo W.png"
favicon_ico: "/assets/images/favicon.ico"

# External navigation links
nav_external_links:
  - title: Baduk / Weiqi Roadmap
    url: https://weiqi.soumyak4.in/
    hide_icon: true 
    

  - title: Buy Me A Coffee
    url: https://www.buymeacoffee.com/SoumyaK4
    hide_icon: true 
    
