title: SoumyaK4
description: Martial Arts for Body & Brain
theme: just-the-docs
color_scheme: dark
url: https://soumyak4.github.io

logo: "/assets/images/Logo W.png"
favicon_ico: "/assets/images/favicon.ico"

# External navigation links
nav_external_links:
  - title: Buy Me A Coffee
    url: https://www.buymeacoffee.com/SoumyaK4
    hide_icon: true 
    
